### ISSUE TITLE
[Refactoring] Better package for command

### ISSUE THREAD

**Issue by insomnius** [kodefluence/altair#18]
**Current condition**

Right now every command are listed in main package

**Wanted condition**

Should be created new package called `command` and then migrate all command from main package to that package.

Feel free to contribute.

**Comment by neo7337** [comment]
Hey @insomnius I would like to work on this project, do you have any discord channel running for discussion?

**Comment by insomnius** [comment]
> Hey @insomnius I would like to work on this project, do you have any discord channel running for discussion?

Currently i don't have any discord channel for this project, but i will create one soon. Thanks for the idea @neo7337

**Comment by neo7337** [comment]
> > Hey @insomnius I would like to work on this project, do you have any discord channel running for discussion?
> 
> Currently i don't have any discord channel for this project, but i will create one soon. Thanks for the idea @neo7337

Lemme know when you have it up and running! @insomnius

**Comment by insomnius** [comment]
Hey @neo7337 you could join our discord channel here. Currently the member is only me.

**Comment by januridp** [comment]
> Hey @neo7337 you could join our discord channel here. Currently the member is only me.
> 
> https://discord.com/invite/jK5TS8X8

Do not paste the bare link, you should tell or refer to the readme

Example:
Hey @blablablablaxxx kindly check our [readme](https://github.com/kodefluence/altair#community) to join our discord channel or you just simply [click here](https://github.com/kodefluence/altair#community)

**Comment by insomnius** [comment]
Nice point @januridp , would do that next time.
