### ISSUE TITLE
Invalid Link Discord Channel 

### ISSUE THREAD

**Issue by januridp** [kodefluence/altair#54]
![Screenshot_2022-12-24-15-38-35-183_com.facebook.katana.jpg](https://user-images.githubusercontent.com/7739709/209428062-96f117db-9263-4a1f-84ea-9feade5d2460.jpg)

**Comment by insomnius** [comment]
Ah thanks @januridp . The correct link is https://discord.gg/Wps4YrQ3SA, would you contribute for this change?

**Comment by januridp** [comment]
> Ah thanks @januridp . The correct link is https://discord.gg/Wps4YrQ3SA, would you contribute for this change?

Sure, I've already sent a PR, kindly check ya
